// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUviUUYUsjNxU4A9ow4UTtvNAtD-byNsk',
    appId: '1:1071759527014:web:227ce2c31b9e72c638b1a7',
    messagingSenderId: '1071759527014',
    projectId: 'premoisaun',
    authDomain: 'premoisaun.firebaseapp.com',
    storageBucket: 'premoisaun.firebasestorage.app',
    measurementId: 'G-GN2HCCMPW4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzU3s81LjauFipYzFhhFdjPyVlWafhOk4',
    appId: '1:1071759527014:android:cbd9fa83e1ac28a838b1a7',
    messagingSenderId: '1071759527014',
    projectId: 'premoisaun',
    storageBucket: 'premoisaun.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNXek2p38I3TqdCQuQ-Zy8x20HzdTRYgc',
    appId: '1:1071759527014:ios:d354325d1b5c74a438b1a7',
    messagingSenderId: '1071759527014',
    projectId: 'premoisaun',
    storageBucket: 'premoisaun.firebasestorage.app',
    iosBundleId: 'com.premio.premio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNXek2p38I3TqdCQuQ-Zy8x20HzdTRYgc',
    appId: '1:1071759527014:ios:d354325d1b5c74a438b1a7',
    messagingSenderId: '1071759527014',
    projectId: 'premoisaun',
    storageBucket: 'premoisaun.firebasestorage.app',
    iosBundleId: 'com.premio.premio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUviUUYUsjNxU4A9ow4UTtvNAtD-byNsk',
    appId: '1:1071759527014:web:a5d79b7ffe5c85dc38b1a7',
    messagingSenderId: '1071759527014',
    projectId: 'premoisaun',
    authDomain: 'premoisaun.firebaseapp.com',
    storageBucket: 'premoisaun.firebasestorage.app',
    measurementId: 'G-3YRPLRQ1G5',
  );
}
